//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.DesignWorks = new HashSet<DesignWork>();
            this.MaterialPriceLogs = new HashSet<MaterialPriceLog>();
        }
    
        public string GUID { get; set; }
        public string TypeID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public sbyte State { get; set; }
    
        public virtual ICollection<DesignWork> DesignWorks { get; set; }
        public virtual ICollection<MaterialPriceLog> MaterialPriceLogs { get; set; }
        public virtual MaterialType MaterialType { get; set; }
    }
}
