//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialPicture
    {
        public string GUID { get; set; }
        public string MaterialColorID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Index { get; set; }
        public string FileName { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public Nullable<int> Top { get; set; }
        public Nullable<int> Left { get; set; }
        public Nullable<int> UploadWidth { get; set; }
        public Nullable<int> UploadHeight { get; set; }
    
        public virtual MaterialColor MaterialColor { get; set; }
    }
}
