//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<DesignWork> DesignWorks { get; set; }
        public DbSet<MaterialColor> MaterialColors { get; set; }
        public DbSet<MaterialPicture> MaterialPictures { get; set; }
        public DbSet<MaterialPriceLog> MaterialPriceLogs { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<MaterialSize> MaterialSizes { get; set; }
        public DbSet<MaterialType> MaterialTypes { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<SingleLogin> SingleLogins { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
